### ISSUE TITLE
Language indicator is missing

### ISSUE THREAD

**Issue by Lyberta** [mate-desktop/libmatekbd#41]
OS: Debian Testing/Buster
libmatekbd: 1.18.2-1

The language indicator is missing. I can get it back if I delete 2nd layout and add it again but that works only until next reboot.

**Comment by monsta** [comment]
Can't reproduce in my Debian Testing VM

**Comment by Lyberta** [comment]
Is there a way for me to provide more info? Maybe MATE keeps some logs?

**Comment by monsta** [comment]
First, check whether the indicator is actually missing from the tray area, or it's there but is invisible.
In the second case there might be a thin area where you can interact with the invisible icon (left-click to change language, right-click to show menu).

**Comment by Lyberta** [comment]
No, it doesn't seem to be there. I have tried moving the tray area and clicking in a lot of places. By the way, it is missing on 2 of my PCs but not missing on one.

**Comment by monsta** [comment]
Ok, it looks the same as https://github.com/mate-desktop/mate-settings-daemon/issues/195. It's reproducible in Debian Testing and Ubuntu 17.10 (which has packages from Debian Unstable). I'll close this one, let's move to that report.
